### ISSUE TITLE
Can‘t find devises After some hours.

### ISSUE THREAD

**Issue by WatsonMD** [twendt/homey-matic#16]
Can‘t find Homematic devises After some  When I restart the App on homey, everything is fine again for some hours.

**Comment by twendt** [comment]
Are you sure that the App did not crash? Does the Homey have a stable WiFi connection. The CCU tends to disconnect clients if it gets timeouts while sending events.
What type of devices do you have connected? We implemented a couple of devices that we do not own, therefore it could also be an issue with one of those devices. Could it be due to a flow that runs every few hours?

**Comment by WatsonMD** [comment]
Maybe it crashed.. It is not in a flow, I have the BI1PBU-FM. I think WIFI is stable. Should I send a Log?

Von meinem iPad gesendet

**Comment by WatsonMD** [comment]
It is Not in Flows,  Maybe the App crashs. I have the 
HM-LC-Bl1PBU-FM

Von meinem iPhone gesendet

**Comment by twendt** [comment]
If crashes then you should see that when you go to the Apps screen in the Homey App. There should be a red message shown and if you click on that then it will show the crash log.
To manually create a log you can also manually install the app with the Athom CLI.

Is that the only device that you have connected?

**Comment by WatsonMD** [comment]
7e23d194-6cdd-4812-8f74-7f15b83ac9f7



Von meinem iPhone gesendet

**Comment by twendt** [comment]
Unfortunately the crash report is empty. Does the configured Homematic device show a red exclamation mark in the Homey App?

**Comment by WatsonMD** [comment]
yes an the App has a break sign in the App overview 



Von meinem iPhone gesendet

**Comment by twendt** [comment]
OK, that means that the app has crashed. Can you please to to the app overview and then into the Homematic app. There you should see a red message stating that the app has crashed. When you click on that message then you should get a black screen and the log should be displayed. Scroll to the bottom and send me a screenshot as a private message in the Athom community please.

**Comment by WatsonMD** [comment]
Unfortunatly there is no red message :(



Von meinem iPad gesendet

**Comment by twendt** [comment]
Can you please create a generic crash report and open a support ticket with Athom with ID? Maybe they can see if the App has crashed or not.
You need to create the report under General and not from the Homematic screen.

**Comment by newatschoen** [comment]
hi timo - i have exact the same issue...

**Comment by twendt** [comment]
Unfortunately I cannot do anything right now. All the crash reports that U got were empty. Therefore I do not know what the issue is as I do not have the issue myself.
Please send general crash report to Athom and ask them if they know what happened.

**Comment by WatsonMD** [comment]
5319BD8252 That is the general Report code, can you contact athom?

Von meinem iPhone gesendet

**Comment by twendt** [comment]
Are you in the Homey Slack by any chance. You can find me as Timo W in there.

**Comment by newatschoen** [comment]
@twendt  I am at the homey slack ;)

**Comment by twendt** [comment]
Version 0.15.0 implements support for using MQTT to connect to the CCU. This requires special configuration in the CCU, but it is much more reliable and also the performance is much better. I recommend using that feature for at least everybody who is facing the issue that the app is crashing. This actually happens due to the memory usage of the app. Homey then kills the app at some point.
